# Generated by Django 6.0.5 on 2026-05-11 21:27

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    common.fields.ULIDField(
                        editable=False, max_length=26, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("user_id", models.CharField(max_length=26, verbose_name="user id")),
                (
                    "account_id",
                    models.CharField(max_length=26, verbose_name="account id"),
                ),
                (
                    "kind",
                    models.CharField(
                        default="semantic",
                        help_text="Listener kind, identifies the Pydantic config class in listeners.registry",
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short label", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Plain-English prompt the engine reads verbatim",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "poll_interval_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="poll interval seconds"
                    ),
                ),
                (
                    "last_polled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last polled at"
                    ),
                ),
                (
                    "next_poll_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="next poll at"
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        default="instant",
                        help_text="'instant' fires notifiers per hit; 'digest' batches on a cadence",
                        max_length=20,
                        verbose_name="delivery mode",
                    ),
                ),
                (
                    "last_digest_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last digest at"
                    ),
                ),
                (
                    "next_digest_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="next digest at"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Typed config blob, validated per `kind` (see listeners.registry)",
                        verbose_name="data",
                    ),
                ),
            ],
            options={
                "verbose_name": "listener",
                "verbose_name_plural": "listeners",
                "indexes": [
                    models.Index(
                        fields=["account_id"], name="listeners_l_account_a7ffc9_idx"
                    ),
                    models.Index(
                        fields=["is_active", "next_poll_at"],
                        name="listeners_l_is_acti_0c2d4f_idx",
                    ),
                    models.Index(
                        fields=["is_active", "delivery_mode", "next_digest_at"],
                        name="listeners_l_is_acti_d39474_idx",
                    ),
                ],
            },
        ),
    ]
