# Generated by Django 6.0.5 on 2026-05-12 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listeners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listener",
            name="poll_interval_seconds",
            field=models.PositiveIntegerField(
                default=300,
                validators=[django.core.validators.MinValueValidator(60)],
                verbose_name="poll interval seconds",
            ),
        ),
    ]
