# Generated by Django 6.0.5 on 2026-06-01 01:31

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('name', models.CharField(help_text='Short label', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('initial_path_id', models.CharField(blank=True, default='', max_length=26, verbose_name='initial path id')),
            ],
            options={
                'verbose_name': 'watch',
                'verbose_name_plural': 'watches',
                'indexes': [models.Index(fields=['account_id', 'id'], name='watch_acct_id_idx'), models.Index(fields=['is_active'], name='watch_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchAction',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('path_id', models.CharField(max_length=26, verbose_name='path id')),
                ('kind', models.CharField(help_text='WatchActionKind value; selects impl + config contract', max_length=32, verbose_name='kind')),
                ('config', models.JSONField(default=dict, help_text='Kind-specific config blob, validated per kind', verbose_name='config')),
                ('rank', models.PositiveIntegerField(help_text='Dense 0-based position within the path', verbose_name='rank')),
            ],
            options={
                'verbose_name': 'watch action',
                'verbose_name_plural': 'watch actions',
                'constraints': [models.UniqueConstraint(fields=('path_id', 'rank'), name='uniq_watchaction_path_rank')],
            },
        ),
        migrations.CreateModel(
            name='WatchActionRun',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('watch_id', models.CharField(max_length=26, verbose_name='watch id')),
                ('action_id', models.CharField(max_length=26, verbose_name='action id')),
                ('feed_item_id', models.CharField(max_length=26, verbose_name='feed item id')),
                ('state', models.CharField(default='pending', help_text='WatchActionRunState value', max_length=16, verbose_name='state')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('result', models.JSONField(default=dict, help_text='Kind-specific result blob', verbose_name='result')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('prior_run_id', models.CharField(blank=True, default='', max_length=26, verbose_name='prior run id')),
            ],
            options={
                'verbose_name': 'watch action run',
                'verbose_name_plural': 'watch action runs',
                'indexes': [models.Index(fields=['state', 'scheduled_at'], name='watchrun_state_sched_idx'), models.Index(fields=['account_id', 'action_id', 'id'], name='watchrun_acct_action_idx')],
                'constraints': [models.UniqueConstraint(fields=('watch_id', 'action_id', 'feed_item_id'), name='uniq_watchactionrun_watch_action_item')],
            },
        ),
        migrations.CreateModel(
            name='WatchFeed',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('watch_id', models.CharField(max_length=26, verbose_name='watch id')),
                ('feed_id', models.CharField(max_length=26, verbose_name='feed id')),
                ('last_item_id', models.CharField(blank=True, default='', max_length=26, verbose_name='last item id')),
            ],
            options={
                'verbose_name': 'watch feed',
                'verbose_name_plural': 'watch feeds',
                'indexes': [models.Index(fields=['account_id', 'feed_id'], name='watchfeed_acct_feed_idx')],
                'constraints': [models.UniqueConstraint(fields=('watch_id', 'feed_id'), name='uniq_watchfeed_watch_feed')],
            },
        ),
        migrations.CreateModel(
            name='WatchPath',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('watch_id', models.CharField(max_length=26, verbose_name='watch id')),
            ],
            options={
                'verbose_name': 'watch path',
                'verbose_name_plural': 'watch paths',
                'indexes': [models.Index(fields=['account_id', 'watch_id'], name='watchpath_acct_watch_idx')],
            },
        ),
    ]
