# Generated by Django 6.0.5 on 2026-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchactionrun',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='attempts'),
        ),
    ]
