# Generated by Django 6.0.5 on 2026-06-02 23:20

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_watchactionrun_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchActionDigestWindow',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('action_id', models.CharField(max_length=26, verbose_name='action id')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='close at')),
            ],
            options={
                'verbose_name': 'watch action digest window',
                'verbose_name_plural': 'watch action digest windows',
                'indexes': [models.Index(fields=['close_at'], name='watchdigestwin_close_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'action_id'), name='uniq_watchdigestwindow_account_action')],
            },
        ),
    ]
