# Generated by Django 6.0.5 on 2026-06-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_watchactiondigestwindow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchactionrun',
            index=models.Index(fields=['account_id', 'action_id', 'state', 'attempts', 'id'], name='watchrun_digest_gather_idx'),
        ),
    ]
