# Generated by Django 6.0.6 on 2026-06-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_watchactionrun_watchrun_digest_gather_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchactionrun',
            index=models.Index(fields=['account_id', 'action_id', 'completed_at'], name='watchrun_activity_idx'),
        ),
    ]
