# Generated by Django 6.0.6 on 2026-06-05 17:40

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_null_retryable_failed_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchactionrun',
            name='delivery_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='delivery id'),
        ),
        migrations.CreateModel(
            name='WatchActionDelivery',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('watch_id', models.CharField(max_length=26, verbose_name='watch id')),
                ('action_id', models.CharField(max_length=26, verbose_name='action id')),
                ('delivery', models.CharField(max_length=16, verbose_name='delivery')),
                ('method', models.CharField(max_length=8, verbose_name='method')),
                ('target_host', models.CharField(blank=True, default='', max_length=255, verbose_name='target host')),
                ('state', models.CharField(default='pending', help_text='WatchActionDeliveryState value', max_length=16, verbose_name='state')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='http status')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='item count')),
                ('attempt', models.PositiveSmallIntegerField(default=0, verbose_name='attempt')),
                ('request_payload', models.JSONField(default=dict, help_text='The WebhookPayload sent (no headers)', verbose_name='request payload')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'watch action delivery',
                'verbose_name_plural': 'watch action deliveries',
                'indexes': [models.Index(fields=['account_id', 'action_id', 'id'], name='watchdeliv_acct_action_idx')],
            },
        ),
    ]
