# Generated by Django 6.0.5 on 2026-05-11 21:27

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    common.fields.ULIDField(
                        editable=False, max_length=26, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("user_id", models.CharField(max_length=26, verbose_name="user id")),
                (
                    "account_id",
                    models.CharField(max_length=26, verbose_name="account id"),
                ),
                (
                    "listener_id",
                    models.CharField(max_length=26, verbose_name="listener id"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Connector kind, e.g. 'reddit_subreddit'",
                        max_length=32,
                        verbose_name="source",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="Observation EVENT_KIND, e.g. 'new_post'",
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=255, verbose_name="external id"),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="occurred at")),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null = pending delivery. Set when all notifiers succeed.",
                        null=True,
                        verbose_name="delivered at",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Full Observation.model_dump()",
                        verbose_name="data",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "indexes": [
                    models.Index(
                        fields=["listener_id", "delivered_at"],
                        name="events_even_listene_92a7fe_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listener_id", "source", "external_id"),
                        name="unique_event_per_listener_source",
                    )
                ],
            },
        ),
    ]
