# Generated by Django 6.0.5 on 2026-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_per_listener_source',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_listene_92a7fe_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='feed_item_id',
            field=models.CharField(default='', max_length=26, verbose_name='feed item id'),
        ),
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.FloatField(blank=True, help_text='Engine relevance score for a hit (null for non-hit kinds)', null=True, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(default=dict, help_text='Deliverable FeedItem/Observation snapshot', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(default='hit', help_text="Event type, e.g. 'hit'", max_length=32, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('kind', 'listener_id', 'feed_item_id'), name='uniq_event_kind_listener_item'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='occurred_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
    ]
