# Generated by Django 6.0.5 on 2026-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_unique_event_per_listener_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(help_text="Event-type discriminator (v1: only 'hit'; future: 'feed_change', 'delivery', ...)", max_length=32, verbose_name='kind'),
        ),
    ]
