# Generated by Django 6.0.5 on 2026-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeners', '0003_rename_description_to_instructions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listener',
            name='listeners_l_is_acti_0c2d4f_idx',
        ),
        migrations.AddField(
            model_name='listener',
            name='last_judged_item_id',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='last judged item id'),
        ),
        migrations.RemoveField(
            model_name='listener',
            name='last_polled_at',
        ),
        migrations.RemoveField(
            model_name='listener',
            name='next_poll_at',
        ),
        migrations.RemoveField(
            model_name='listener',
            name='poll_interval_seconds',
        ),
    ]
