# Generated by Django 6.0.5 on 2026-05-22 14:46

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('kind', models.CharField(default='curated', help_text='Feed kind, identifies the Pydantic config class in feeds.registry', max_length=32, verbose_name='kind')),
                ('name', models.CharField(help_text='Short label', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60)], verbose_name='poll interval seconds')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='last polled at')),
                ('next_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='next poll at')),
                ('data', models.JSONField(default=dict, help_text='Typed config blob (streams + retention), validated per `kind` (see feeds.registry)', verbose_name='data')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
                'indexes': [models.Index(fields=['account_id'], name='feeds_feed_account_5b776a_idx'), models.Index(fields=['is_active', 'next_poll_at'], name='feeds_feed_is_acti_9b67a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feed_id', models.CharField(max_length=26, verbose_name='feed id')),
                ('source', models.CharField(max_length=64, verbose_name='source')),
                ('external_id', models.CharField(max_length=255, verbose_name='external id')),
                ('stream_key', models.CharField(default='', max_length=255, verbose_name='stream key')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='occurred at')),
                ('data', models.JSONField(default=dict, help_text='Connector Observation dump', verbose_name='data')),
            ],
            options={
                'verbose_name': 'feed item',
                'verbose_name_plural': 'feed items',
                'constraints': [models.UniqueConstraint(fields=('feed_id', 'source', 'external_id'), name='uniq_feeditem_per_feed_source_external')],
            },
        ),
    ]
