# Generated by Django 6.0.5 on 2026-06-01 01:42

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user_id', models.CharField(max_length=26, verbose_name='user id')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('kind', models.CharField(default='curated', help_text='Feed kind, identifies the Pydantic config class in feeds.registry', max_length=32, verbose_name='kind')),
                ('name', models.CharField(help_text='Short label', max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60)], verbose_name='poll interval seconds')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='last polled at')),
                ('next_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='next poll at')),
                ('data', models.JSONField(default=dict, help_text='Typed config blob (streams + retention), validated per `kind` (see feeds.registry)', verbose_name='data')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
                'indexes': [models.Index(fields=['account_id'], name='feeds_feed_account_5b776a_idx'), models.Index(fields=['is_active', 'next_poll_at'], name='feeds_feed_is_acti_9b67a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('feed_id', models.CharField(max_length=26, verbose_name='feed id')),
                ('source_kind', models.CharField(max_length=64, verbose_name='source kind')),
                ('external_id', models.CharField(max_length=255, verbose_name='external id')),
                ('source_label', models.CharField(default='', max_length=255, verbose_name='source label')),
                ('source_meta', models.JSONField(blank=True, default=dict, verbose_name='source meta')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='occurred at')),
                ('data', models.JSONField(default=dict, help_text='Connector SourcePayload dump', verbose_name='data')),
            ],
            options={
                'verbose_name': 'feed item',
                'verbose_name_plural': 'feed items',
                'indexes': [models.Index(fields=['account_id', 'feed_id', 'id'], name='feeditem_acct_feed_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('feed_id', 'source_kind', 'external_id'), name='uniq_feeditem_per_feed_source_external')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('feed_id', models.CharField(max_length=26, verbose_name='feed id')),
                ('kind', models.CharField(help_text='Denormalized from spec; matches the SourceSpec discriminator', max_length=32, verbose_name='kind')),
                ('spec', models.JSONField(help_text='Full SourceSpec dump (includes kind for round-trip via the discriminated union)', verbose_name='spec')),
                ('spec_hash', models.CharField(help_text='sha256 of the canonical spec dump; unique within (account_id, feed_id)', max_length=64, verbose_name='spec hash')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='last event at')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Operator-supplied tags; copied onto each FeedItem this source produces', verbose_name='meta')),
                ('field_map', models.JSONField(blank=True, default=dict, help_text="Connector-readable hints; overrides the feed's default_field_map per key", verbose_name='field map')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'indexes': [models.Index(fields=['account_id', 'feed_id', 'id'], name='feeds_sourc_acct_feed_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'feed_id', 'spec_hash'), name='uniq_account_feed_spec_hash')],
            },
        ),
    ]
