# Generated by Django 6.0.5 on 2026-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['feed_id', 'id'], name='feeditem_feed_id_id_idx'),
        ),
    ]
