# Generated by Django 6.0.5 on 2026-05-28 21:18

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_backfill_stream_watermarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "spec",
                    models.JSONField(
                        help_text="SourceSpec dump (validates against the SourceSpec union)", verbose_name="spec"
                    ),
                ),
                (
                    "spec_key",
                    models.CharField(
                        help_text="Canonical spec.model_dump_json(); unique within a feed",
                        max_length=512,
                        verbose_name="spec key",
                    ),
                ),
                ("last_event_at", models.DateTimeField(blank=True, null=True, verbose_name="last event at")),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operator-supplied tags; copied onto each FeedItem this source produces",
                        verbose_name="meta",
                    ),
                ),
                (
                    "field_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connector-readable hints; overrides the feed's default_field_map per key",
                        verbose_name="field map",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="feeds.feed",
                        verbose_name="feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "source",
                "verbose_name_plural": "sources",
                "indexes": [models.Index(fields=["feed", "id"], name="feeds_sourc_feed_id_321dd7_idx")],
                "constraints": [models.UniqueConstraint(fields=("feed", "spec_key"), name="uniq_feed_spec")],
            },
        ),
    ]
