# Generated by Django 6.0.5 on 2026-05-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_streams_to_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeditem",
            name="stream_meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="stream meta"),
        ),
    ]
