# Generated by Django 6.0.5 on 2026-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_feeditem_rename_source_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='source_kind',
            field=models.CharField(max_length=64, verbose_name='source kind'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source_label',
            field=models.CharField(default='', max_length=255, verbose_name='source label'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='source meta'),
        ),
        migrations.AlterField(
            model_name='source',
            name='account_id',
            field=models.CharField(max_length=26, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='source',
            name='feed_id',
            field=models.CharField(max_length=26, verbose_name='feed id'),
        ),
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(help_text='Denormalized from spec; matches the SourceSpec discriminator', max_length=32, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='source',
            name='spec',
            field=models.JSONField(help_text='Full SourceSpec dump (includes kind for round-trip via the discriminated union)', verbose_name='spec'),
        ),
        migrations.AlterField(
            model_name='source',
            name='spec_hash',
            field=models.CharField(help_text='sha256 of the canonical spec dump; unique within (account_id, feed_id)', max_length=64, verbose_name='spec hash'),
        ),
    ]
