# Generated by Django 6.0.5 on 2026-05-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_canonicalize_source_spec_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='source',
            name='feeds_sourc_kind_idx',
        ),
    ]
