# Generated by Django 6.0.5 on 2026-06-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_remove_source_feeds_sourc_kind_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='data',
            field=models.JSONField(default=dict, help_text='Connector SourcePayload dump', verbose_name='data'),
        ),
    ]
